{
 "title": "3Scale LAST EDIT",
 "description": "modificate variabili e query",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{namespace=~\".*3scale.*\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(nginx_http_connections{namespace=~\".*3scale.*\"}, pod)"
    }
   },
   {
    "name": "httpCode",
    "label": "httpCode",
    "query": {
     "query": "label_values(upstream_status_total, status)"
    }
   },
   {
    "name": "time_range",
    "label": "Interval",
    "query": "5s,10s,30s,1m,5m,15m,30m,1h,2h,1d"
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(upstream_status_total, service_system_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Apicast Staging",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count (worker_process {pod=~\"$pod\", service=\"apicast-staging\"})"
      }
     ]
    },
    {
     "title": "Apicast Production",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count (worker_process {pod=~\"$pod\", service=\"apicast-production\"})"
      }
     ]
    }
   ]
  },
  { "title": "Connections Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Http Code OK",
   "type": "timeseries",
   "description": "Number of 200/300 http codes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(upstream_status_total{status=~\"2.*\", status=~\"$httpCode\", pod=~\"$pod\", namespace=~\"$namespace\"}[$time_range])) by (status)",
     "legendFormat": "Code: {{ status }}"
    },
    {
     "expr": "sum(increase(upstream_status_total{status=~\"3.*\", status=~\"$httpCode\", pod=~\"$pod\", namespace=~\"$namespace\"}[$time_range])) by (status)",
     "legendFormat": "Code: {{ status }}"
    }
   ]
  },
  {
   "title": "Http Code Failed",
   "type": "timeseries",
   "description": "Number of 400/500 http codes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(upstream_status_total{status=~\"4.*\", status=~\"$httpCode\", pod=~\"$pod\", namespace=~\"$namespace\"}[$time_range])) by (status)",
     "legendFormat": "Code: {{ status }}"
    },
    {
     "expr": "sum(increase(upstream_status_total{status=~\"5.*\", status=~\"$httpCode\", pod=~\"$pod\", namespace=~\"$namespace\"}[$time_range])) by (status)",
     "legendFormat": "Code: {{ status }}"
    }
   ]
  },
  {
   "title": "Ngnix Error Log",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(nginx_error_log_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$time_range])) by (level)",
     "legendFormat": "{{ pod }} {{ level }}"
    }
   ]
  },
  {
   "title": "Connections details (by Http Code)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Http Code $httpCode",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
     "repeat": "httpCode",
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(upstream_status_total{namespace=~\"$namespace\", pod=~\"$pod\", status=~\"$httpCode\"})",
       "legendFormat": "{{ status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections details (by Service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
     "repeat": "service",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      {
       "expr": "sum(upstream_status_total{namespace=~\"$namespace\", status=~\"2.*|3.*\", status=~\"$httpCode\", service_system_name=~\"$service\"})"
      },
      {
       "expr": "-sum(upstream_status_total{namespace=~\"$namespace\", status=~\"4.*|5.*\", status=~\"$httpCode\", service_system_name=~\"$service\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Percentages on total 3scale http connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Percentage of 200/300 http codes",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100*sum(upstream_status_total{pod=~\"$pod\", status=~\"2.*|3.*\"})/sum(upstream_status_total{pod=~\"$pod\"})"
      }
     ]
    },
    {
     "title": "Percentage of 400/500 http codes",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100*sum(upstream_status_total{pod=~\"$pod\", status=~\"4.*|5.*\"})/sum(upstream_status_total{pod=~\"$pod\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Detailed Percentages on total 3scale http connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Percentage of $httpCode http codes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
     "repeat": "httpCode",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100*sum(upstream_status_total{pod=~\"$pod\", status=~\"$httpCode\"})/sum(upstream_status_total{pod=~\"$pod\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Detailed percentages (by Service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
     "repeat": "service",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100*sum(upstream_status_total{namespace=~\"$namespace\", pod=~\"$pod\", status=~\"2.*|3.*\", status=~\"$httpCode\", service_system_name=~\"$service\"})/sum(upstream_status_total{namespace=~\"$namespace\", pod=~\"$pod\", service_system_name=~\"$service\"})",
       "legendFormat": "Passed"
      },
      {
       "expr": "100*sum(upstream_status_total{namespace=~\"$namespace\", pod=~\"$pod\", status=~\"4.*|5.*\", status=~\"$httpCode\", service_system_name=~\"$service\"})/sum(upstream_status_total{namespace=~\"$namespace\", pod=~\"$pod\", service_system_name=~\"$service\"})",
       "legendFormat": "Failed"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections details(Graphics)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Http Code $httpCode",
     "type": "timeseries",
     "description": "Number of $httpCode http codes",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
     "repeat": "httpCode",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(upstream_status_total{status=~\"$httpCode\", pod=~\"$pod\", namespace=~\"$namespace\"}[$time_range])) by (status)",
       "legendFormat": "Code: {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream Status (General)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "3Scale Backend Calls Counter",
     "type": "timeseries",
     "description": "Calls to the 3scale backend",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(threescale_backend_calls_total{namespace=~\"$namespace\", pod=~\"$pod\", status=~\"2.*|3.*\"}[$time_range])) by (status)",
       "legendFormat": "Code {{ status }}"
      },
      {
       "expr": "-sum(increase(threescale_backend_calls_total{namespace=~\"$namespace\", pod=~\"$pod\", status=~\"4.*|5.*\"}[$time_range])) by (status)",
       "legendFormat": "Code {{ status }}"
      }
     ]
    },
    {
     "title": "Upstream Status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(upstream_status_total{namespace=~\"$namespace\", status=~\"2.*|3.*\", pod=~\"$pod\"}[$time_range])) by (status)",
       "legendFormat": "Code: {{ status }}"
      },
      {
       "expr": "-sum(increase(upstream_status_total{namespace=~\"$namespace\", status!~\"2.*|3.*\", pod=~\"$pod\"}[$time_range])) by (status)",
       "legendFormat": "Code: {{ status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream Status (by Service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "repeat": "service",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(upstream_status_total{namespace=~\"$namespace\", pod=~\"$pod\", status=~\"2.*|3.*\", status=~\"$httpCode\", service_system_name=~\"$service\"}[$time_range])) by (status)",
       "legendFormat": "Code: {{ status }}"
      },
      {
       "expr": "-sum(increase(upstream_status_total{namespace=~\"$namespace\", pod=~\"$pod\", status=~\"4.*|5.*\", status=~\"$httpCode\", service_system_name=~\"$service\"}[$time_range])) by (status)",
       "legendFormat": "Code:  {{ status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Total response time seconds (by Service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service Response Time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "repeat": "service",
     "targets": [
      {
       "expr": "total_response_time_seconds{namespace=~\"$namespace\", service_system_name=~\"$service\"}",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Response times from upstream servers (by service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service Response Time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
     "repeat": "service",
     "targets": [
      {
       "expr": "upstream_response_time_seconds{service_system_name=~\"$service\"}",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nginx Http Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total HTTP connections",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(nginx_http_connections{namespace=~\"$namespace\", pod=~\"$pod\", state=\"total\"}[$time_range]))",
       "legendFormat": "apicast-production"
      }
     ]
    },
    {
     "title": "Accepted HTTP connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(nginx_http_connections{namespace=~\"$namespace\", pod=~\"$pod\", state=\"accepted\"}[$time_range]))",
       "legendFormat": "apicast-production"
      }
     ]
    },
    {
     "title": "Active HTTP connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(nginx_http_connections{namespace=~\"$namespace\", pod=~\"$pod\", state=\"active\"}[$time_range]))",
       "legendFormat": "apicast-production"
      }
     ]
    },
    {
     "title": "Reading HTTP connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(nginx_http_connections{namespace=~\"$namespace\", pod=~\"$pod\", state=\"reading\"}[$time_range]))",
       "legendFormat": "apicast-production"
      }
     ]
    },
    {
     "title": "Writing HTTP connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(nginx_http_connections{namespace=~\"$namespace\", pod=~\"$pod\", state=\"writing\"}[$time_range]))",
       "legendFormat": "apicast-production"
      }
     ]
    },
    {
     "title": "Waiting HTTP connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(nginx_http_connections{namespace=~\"$namespace\", pod=~\"$pod\", state=\"waiting\"}[$time_range]))",
       "legendFormat": "apicast-production"
      }
     ]
    },
    {
     "title": "Handled HTTP connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(nginx_http_connections{namespace=~\"$namespace\", pod=~\"$pod\", state=\"handled\"}[$time_range]))",
       "legendFormat": "apicast-production"
      }
     ]
    },
    {
     "title": "Number of nginx-lua-prometheus errors",
     "type": "timeseries",
     "description": "Number of nginx-lua-prometheus errors",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(nginx_metric_errors_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$time_range])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Response Time Buckets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total response time $pod",
     "type": "heatmap",
     "description": "Response times from upstream servers",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
     "repeat": "pod",
     "targets": [
      {
       "expr": "total_response_time_seconds{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream Response Time Buckets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upstream response time $pod",
     "type": "heatmap",
     "description": "Response times from upstream servers",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 15 },
     "repeat": "pod",
     "targets": [
      {
       "expr": "upstream_response_time_seconds{namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OpenResty shared dictionary free space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Api Keys",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100 * openresty_shdict_free_space{dict=\"api_keys\", pod=~\"$pod\", namespace=~\"$namespace\"} / openresty_shdict_capacity{dict=\"api_keys\", pod=~\"$pod\", namespace=~\"$namespace\"} ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Batched Reports",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100 * openresty_shdict_free_space{dict=\"batched_reports\", pod=~\"$pod\", namespace=~\"$namespace\"} / openresty_shdict_capacity{dict=\"batched_reports\", pod=~\"$pod\", namespace=~\"$namespace\"} ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Batched Reports Locks",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100 * openresty_shdict_free_space{dict=\"batched_reports_locks\", pod=~\"$pod\", namespace=~\"$namespace\"} / openresty_shdict_capacity{dict=\"batched_reports_locks\", pod=~\"$pod\", namespace=~\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Cached Auths",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100 * openresty_shdict_free_space{dict=\"cached_auths\", pod=~\"$pod\", namespace=~\"$namespace\"} / openresty_shdict_capacity{dict=\"cached_auths\", pod=~\"$pod\", namespace=~\"$namespace\"} ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Configuration",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100 * openresty_shdict_free_space{dict=\"configuration\", pod=~\"$pod\", namespace=~\"$namespace\"} / openresty_shdict_capacity{dict=\"configuration\", pod=~\"$pod\", namespace=~\"$namespace\"} ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Init",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100 * openresty_shdict_free_space{dict=\"init\", pod=~\"$pod\", namespace=~\"$namespace\"} / openresty_shdict_capacity{dict=\"init\", pod=~\"$pod\", namespace=~\"$namespace\"} ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Limiter",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100 * openresty_shdict_free_space{dict=\"limiter\", pod=~\"$pod\", namespace=~\"$namespace\"} / openresty_shdict_capacity{dict=\"limiter\", pod=~\"$pod\", namespace=~\"$namespace\"} ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Locks",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100 * openresty_shdict_free_space{dict=\"locks\", pod=~\"$pod\", namespace=~\"$namespace\"} / openresty_shdict_capacity{dict=\"locks\", pod=~\"$pod\", namespace=~\"$namespace\"} ",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Prometheus Metrics",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100 * openresty_shdict_free_space{dict=\"prometheus_metrics\", pod=~\"$pod\", namespace=~\"$namespace\"} / openresty_shdict_capacity{dict=\"prometheus_metrics\", pod=~\"$pod\", namespace=~\"$namespace\"} ",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}