{
 "title": "TIROCINIO",
 "description": "modificate variabili e query",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "httpCode",
    "label": "httpCode",
    "query": {
     "query": "label_values(upstream_status_total, status)"
    }
   },
   {
    "name": "time_range",
    "label": "Interval",
    "query": "5s,10s,30s,1m,5m,15m,30m,1h,2h,1d"
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(upstream_status_total, service_system_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Connections Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Http Code OK",
   "type": "timeseries",
   "description": "Number of 200/300 http codes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(upstream_status_total{status=~\"2.*\", status=~\"$httpCode\"}[$time_range])) by (status)",
     "legendFormat": "Code: {{ status }}"
    },
    {
     "expr": "sum(increase(upstream_status_total{status=~\"3.*\", status=~\"$httpCode\"}[$time_range])) by (status)",
     "legendFormat": "Code: {{ status }}"
    }
   ]
  },
  {
   "title": "Http Code Failed",
   "type": "timeseries",
   "description": "Number of 400/500 http codes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(upstream_status_total{status=~\"4.*\", status=~\"$httpCode\"}[$time_range])) by (status)",
     "legendFormat": "Code: {{ status }}"
    },
    {
     "expr": "sum(increase(upstream_status_total{status=~\"5.*\", status=~\"$httpCode\"}[$time_range])) by (status)",
     "legendFormat": "Code: {{ status }}"
    }
   ]
  },
  {
   "title": "Ngnix Error Log",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(nginx_error_log_total{}[$time_range])) by (level)",
     "legendFormat": "{{ pod }} {{ level }}"
    }
   ]
  },
  {
   "title": "Connections details (by Http Code)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Http Code $httpCode",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
     "repeat": "httpCode",
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(upstream_status_total{status=~\"$httpCode\"})",
       "legendFormat": "{{ status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections details (by Service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
     "repeat": "service",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      {
       "expr": "sum(upstream_status_total{status=~\"2.*|3.*\", status=~\"$httpCode\", service_system_name=~\"$service\"})"
      },
      {
       "expr": "-sum(upstream_status_total{status=~\"4.*|5.*\", status=~\"$httpCode\", service_system_name=~\"$service\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Percentages on total 3scale http connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Percentage of 200/300 http codes",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100*sum(upstream_status_total{status=~\"2.*|3.*\"})/sum(upstream_status_total{})"
      }
     ]
    },
    {
     "title": "Percentage of 400/500 http codes",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100*sum(upstream_status_total{status=~\"4.*|5.*\"})/sum(upstream_status_total{})"
      }
     ]
    }
   ]
  },
  {
   "title": "Detailed Percentages on total 3scale http connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Percentage of $httpCode http codes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
     "repeat": "httpCode",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100*sum(upstream_status_total{status=~\"$httpCode\"})/sum(upstream_status_total{})"
      }
     ]
    }
   ]
  },
  {
   "title": "Detailed percentages (by Service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
     "repeat": "service",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100*sum(upstream_status_total{status=~\"2.*|3.*\", status=~\"$httpCode\", service_system_name=~\"$service\"})/sum(upstream_status_total{ service_system_name=~\"$service\"})",
       "legendFormat": "Passed"
      },
      {
       "expr": "100*sum(upstream_status_total{status=~\"4.*|5.*\", status=~\"$httpCode\", service_system_name=~\"$service\"})/sum(upstream_status_total{service_system_name=~\"$service\"})",
       "legendFormat": "Failed"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections details(Graphics)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Http Code $httpCode",
     "type": "timeseries",
     "description": "Number of $httpCode http codes",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
     "repeat": "httpCode",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(upstream_status_total{status=~\"$httpCode\"}[$time_range])) by (status)",
       "legendFormat": "Code: {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream Status (General)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "3Scale Backend Calls Counter",
     "type": "timeseries",
     "description": "Calls to the 3scale backend",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(threescale_backend_calls_total{status=~\"2.*|3.*\"}[$time_range])) by (status)",
       "legendFormat": "Code {{ status }}"
      },
      {
       "expr": "-sum(increase(threescale_backend_calls_total{status=~\"4.*|5.*\"}[$time_range])) by (status)",
       "legendFormat": "Code {{ status }}"
      }
     ]
    },
    {
     "title": "Upstream Status",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(upstream_status_total{status=~\"2.*|3.*\"}[$time_range])) by (status)",
       "legendFormat": "Code: {{ status }}"
      },
      {
       "expr": "-sum(increase(upstream_status_total{status!~\"2.*|3.*\"}[$time_range])) by (status)",
       "legendFormat": "Code: {{ status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Upstream Status (by Service)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "repeat": "service",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(upstream_status_total{status=~\"2.*|3.*\", status=~\"$httpCode\", service_system_name=~\"$service\"}[$time_range])) by (status)",
       "legendFormat": "Code: {{ status }}"
      },
      {
       "expr": "-sum(increase(upstream_status_total{status=~\"4.*|5.*\", status=~\"$httpCode\", service_system_name=~\"$service\"}[$time_range])) by (status)",
       "legendFormat": "Code:  {{ status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Total response time seconds (by Service) NON FUNGE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service Response Time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "repeat": "service",
     "targets": [
      {
       "expr": "total_response_time_seconds{service_system_name=~\"$service\"}",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Response times from upstream servers (by service) NON FUNGE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service Response Time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
     "repeat": "service",
     "targets": [
      {
       "expr": "upstream_response_time_seconds{service_system_name=~\"$service\"}",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nginx Http Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total HTTP connections",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(nginx_http_connections{state=\"total\"}[$time_range]))",
       "legendFormat": "apicast-production"
      }
     ]
    },
    {
     "title": "Accepted HTTP connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(nginx_http_connections{state=\"accepted\"}[$time_range]))",
       "legendFormat": "apicast-production"
      }
     ]
    },
    {
     "title": "Active HTTP connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(nginx_http_connections{state=\"active\"}[$time_range]))",
       "legendFormat": "apicast-production"
      }
     ]
    },
    {
     "title": "Reading HTTP connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(nginx_http_connections{ state=\"reading\"}[$time_range]))",
       "legendFormat": "apicast-production"
      }
     ]
    },
    {
     "title": "Writing HTTP connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(nginx_http_connections{state=\"writing\"}[$time_range]))",
       "legendFormat": "apicast-production"
      }
     ]
    },
    {
     "title": "Waiting HTTP connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(nginx_http_connections{state=\"waiting\"}[$time_range]))",
       "legendFormat": "apicast-production"
      }
     ]
    },
    {
     "title": "Handled HTTP connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(nginx_http_connections{state=\"handled\"}[$time_range]))",
       "legendFormat": "apicast-production"
      }
     ]
    },
    {
     "title": "Number of nginx-lua-prometheus errors",
     "type": "timeseries",
     "description": "Number of nginx-lua-prometheus errors",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(nginx_metric_errors_total{}[$time_range])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}